### ISSUE TITLE
Reading the master password from stdin

### ISSUE THREAD

**Issue by jeremydavis519** [71/lesspass.rs#1]
Hello. I'm interested in using this crate to manage my passwords, but I noticed that it requires the master password to be an argument in the initial command. As a result, it is fully visible and is stored in the command line history. I would like it to be able to read the master password from standard input without echoing the characters, like most command-line utilities that take passwords do.

Based on a cursory reading of the source code, it shouldn't be too hard to add a case for when the password isn't one of the arguments, and I found the [`rpassword`](https://crates.io/crates/rpassword) crate, which is designed for this kind of input. I'll see if it's as simple as I think. If it is, you can expect a pull request in the next few days.

**Comment by 71** [comment]
Actually that case is already handled, see [here](https://github.com/71/lesspass.rs/blob/master/src/main.rs#L183). Although the characters you write aren't hidden, it's true.

I don't mind adding a dependency to `rpassword`, and unless you've already started on your side, I can probably have it done by the end of the day.

**Comment by 71** [comment]
I actually had a few tweaks I wanted to apply to the rest of the CLI, so I went ahead and added `rpassword` support myself.
